apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-web
  labels:
    app: web
  {{- include "mychart.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: {{ .Values.web.type }}
  selector:
    app: web
  {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.web.ports | toYaml | nindent 2 -}}